### ISSUE TITLE
Sort order settings

### ISSUE THREAD

**Issue by tdksk** [nickcernis/github-cli-ui#1]
It appears that list items are displayed in ascending order by PR number, but I would like to display them in descending order (same as the default order of the `gh pr list` command), so it would be great to be able to configure the sort order.

https://github.com/nickcernis/github-cli-ui/blob/df784443254d1efce14569741a6a2485f038dab3/src/pr/pickers.ts#L100

**Comment by nickcernis** [comment]
Thanks for the suggestion, @tdksk!

I just released 0.3.1 with this change. It now sorts in descending order by default. There's no extra setting to change.

**Comment by tdksk** [comment]
Thank you for the change! It is more convenient for me.
